Repository wecode-bootcamp-korea/14-1st-StyleCode-backend, pull requests merged in 2020-11, with the labels that each got.

#1 Feature/model
  cart/__init__.py
  cart/admin.py
  cart/apps.py
  cart/migrations/0001_initial.py
  cart/migrations/0002_auto_20201117_2255.py
  cart/migrations/0003_auto_20201118_1136.py
  cart/migrations/0004_auto_20201118_1607.py
  cart/migrations/__init__.py
  cart/models.py
  cart/tests.py
  cart/views.py
  ootd/__init__.py
  ootd/admin.py
  ootd/apps.py
  ootd/migrations/0001_initial.py
  ootd/migrations/0002_auto_20201117_2255.py
  ootd/migrations/0003_auto_20201118_1118.py
  ootd/migrations/0004_auto_20201118_1429.py
  ootd/migrations/0005_auto_20201118_1607.py
  ootd/migrations/__init__.py
  ootd/models.py
  ootd/tests.py
  ootd/views.py
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/0002_remove_product_cart.py
  product/migrations/0003_auto_20201118_1607.py
  product/migrations/0004_auto_20201118_1610.py
  product/migrations/0005_auto_20201118_1613.py
  product/migrations/0006_product_like.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  stylecode/settings.py
  stylecode/urls.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201118_1118.py
  user/migrations/0003_auto_20201118_1136.py
  user/migrations/0004_auto_20201118_1607.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청, Status: 수정 요청

#6 Feature/product detail
  cart/migrations/0001_initial.py
  cart/migrations/0002_auto_20201121_1609.py
  cart/views.py
  ootd/migrations/0001_initial.py
  ootd/migrations/0002_auto_20201121_1609.py
  ootd/models.py
  product/migrations/0001_initial.py
  product/models.py
  product/urls.py
  product/views.py
  stylecode/settings.py
  stylecode/urls.py
  user/migrations/0001_initial.py
Labels: Status: Accepted

#7 Feature/ootd
  .gitignore
  cart/migrations/0001_initial.py
  cart/migrations/0002_auto_20201119_2005.py
  cart/migrations/0002_auto_20201121_1609.py
  cart/migrations/0002_auto_20201124_1716.py
  cart/models.py
  ootd/admin.py
  ootd/migrations/0001_initial.py
  ootd/migrations/0002_auto_20201118_1932.py
  ootd/migrations/0002_auto_20201121_1609.py
  ootd/migrations/0002_auto_20201124_1716.py
  ootd/models.py
  ootd/tests.py
  ootd/urls.py
  ootd/views.py
  order/migrations/0001_initial.py
  product/migrations/0001_initial.py
  product/models.py
  stylecode/settings.py
  stylecode/urls.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201118_2155.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#9 Feature/cart
  .gitignore
  cart/migrations/0002_auto_20201123_0025.py
  cart/models.py
  cart/urls.py
  cart/views.py
  ootd/migrations/0002_auto_20201123_0025.py
  order/migrations/0001_initial.py
  product/migrations/0001_initial.py
  requirements/requirements.txt
  stylecode/settings.py
  stylecode/urls.py
  user/migrations/0001_initial.py
Labels: Status: 수정 요청

#13 Add : ID Check 추가
  user/views.py
Labels: Status: 리뷰 요청

#11 Feature/search
  cart/migrations/0001_initial.py
  cart/migrations/0002_auto_20201124_1706.py
  cart/migrations/0002_auto_20201124_1716.py
  cart/migrations/0002_auto_20201126_1558.py
  cart/migrations/0003_auto_20201126_1607.py
  cart/models.py
  cart/views.py
  ootd/migrations/0001_initial.py
  ootd/migrations/0002_auto_20201124_1706.py
  ootd/migrations/0002_auto_20201124_1716.py
  ootd/migrations/0002_auto_20201126_1558.py
  order/migrations/0001_initial.py
  product/migrations/0001_initial.py
  product/urls.py
  product/views.py
  search/__init__.py
  search/admin.py
  search/apps.py
  search/migrations/__init__.py
  search/models.py
  search/tests.py
  search/urls.py
  search/views.py
  stylecode/settings.py
  stylecode/urls.py
  user/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#18 Modify: 실수 수정
  .DS_Store
  cart/views.py
  ootd/urls.py
  ootd/views.py
  product/urls.py
Labels: Status: 리뷰 요청
